version: '3'
services:

  backend:
    image: '322456/signalonebackend:dev'
    restart: on-failure
    ports:
      - 443:443
      - 80:80
    depends_on:
      - solutions-agent
    volumes:
      - /certs:/certs

  solutions-agent:
      image: '322456/solutions-agent:dev'
      restart: on-failure
      ports:
        - 8081:8081
